model {
  file: "model.sdf"
}
name: "PEPSI_NEXT_CACRV"
description: "PEPSI NEXT (CA+CRV)"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PEPSI"
}
annotations {
  key: "gtin"
  value: "00012000150296"
}
annotations {
  key: "sku"
  value: "00012000150296"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
