#!/usr/bin/env python3
import json
import base64
from openai import OpenAI

# ============================================================
# USER COMMAND
# ============================================================

user_command = "burger robots gather around the round table to discuss strategy."

STATE_PATH = "state.json"
MAP_JSON_PATH = "map_v2_full_without_robot.json"
MAP_PNG_PATH = "map_v2_full_without_robot.png"

MODEL = "gpt-4.1"

client = OpenAI()


# ============================================================
# Load files
# ============================================================

def load_json(p):
    with open(p) as f:
        return json.load(f)

state = load_json(STATE_PATH)
map_json = load_json(MAP_JSON_PATH)


# ============================================================
# PNG to vision input
# ============================================================

def png_to_dataurl(path):
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    return f"data:image/png;base64,{b64}"


# ============================================================
# LLM SYSTEM PROMPT (GENERIC + FORMATION AWARE)
# ============================================================

SYSTEM_PROMPT = """
You are a Navigation Manager for a multi-robot system.

You receive:
- user_command (task)
- state (robot poses and formations)
- map_json (semantic objects)
- map_png (visual layout of the map)

Your job: assign goal poses.

Method:

Robot:
 - interpret task
 - locate relevant object
 - choose reasonable approach pose
 - output x,y,yaw

Formation:
 - output centroid_x, centroid_y, centroid_yaw
 - output desired_radius
 - compute scale sx,sy

If surround task:
 - centroid may be at object

If assembly:
 - only assign those robots

Output ONLY valid JSON:

{
 "robots": { "name": {"x":..,"y":..,"yaw":..,"reason":""} },
 "formations": {
   "name":{
     "centroid_x":..,
     "centroid_y":..,
     "centroid_yaw":..,
     "desired_radius":..,
     "scale":{"sx":..,"sy":..},
     "reason":""
   }
 },
 "notes":""
}
"""


# ============================================================
# Call LLM (vision + text)
# ============================================================

def call_llm(payload):
    img = png_to_dataurl(MAP_PNG_PATH)

    r = client.responses.create(
        model=MODEL,
        instructions=SYSTEM_PROMPT,
        input=[{
            "role":"user",
            "content":[
                {"type":"input_text","text":json.dumps(payload)},
                {"type":"input_image","image_url":img}
            ]
        }]
    )

    text = r.output_text.strip()

    if text.startswith("```"):
        text = text.split("```")[1]

    return json.loads(text)


# ============================================================
# Navigation Manager (PURE LLM)
# ============================================================

def navigation_manager():

    if not user_command.strip():
        return {"robots":{}, "formations":{}, "notes":"no task"}

    payload = {
        "user_command": user_command,
        "state": state,
        "map_json": map_json
    }

    goals = call_llm(payload)

    goals["notes"] = "generated by LLM (no geometric validation)"

    return goals


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    goals = navigation_manager()

    print("\nUSER COMMAND:")
    print(user_command)

    print("\nLLM GENERATED GOALS:")
    print(json.dumps(goals, indent=2))
